### ISSUE TITLE
Incorrect value for mk8dx.data.Track

### ISSUE THREAD

**Issue by Subaru8556** [sheat-git/mk8dx.py#1]
mk8dx.data.Track に以下の誤りの可能性がある値が設定されています
次の修正が必要だと思いますので、問題がなければ反映をお願いします
```
SCC.name
Sweet Sweet Canion -> Sweet Sweet Canyon

RDP3.name
Dounut Plains 3 -> Donut Plains 3

RRRD.console
None -> Console.N64
```

BNH(ニンニンドージョー), BSHS(アイスビルディング), BMM(メリーメリーマウンテン) の console の値に関しても1つ疑問点があります
現時点では、
```
BNH : None
BSHS : None
BMM : console.TOUR
```
となっていますが、

英語で表記する際、実在の場所に基づいていないマリオカートツアーのコースに関しては Tour の表記がないため
```
BNH : None
BSHS : None
BMM : None
```
が正しくなるのではないでしょうか

**Comment by oha-4** [comment]
すみません、全然気づいていませんでした。。
修正しました！
